### ISSUE TITLE
[Android] "Syncing..." message wrongly loops continuously in the side bar after you delete and undo a note

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/notes#1116]
**[Affected Platforms]:**
- Pixel (Android 8.0.0)
- Samsung S8 (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2303) installed.
- Have one note created.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Open the note and tap the "Delete" button.
3. Tap on the "Undo" button.
4. Swipe from left to right and observe the bottom part of the panel.

**[Expected result]:**
- The "Synced at [Hour]" message is displayed.

**[Actual result]:**
- The "Syncing changes..." message is displayed in a continuous loop.

**[Notes]:**
- If you sync the aplication from the note list view by swipping down the "Synced at [Hour]" message will be displayed.
- Attached a screen recording of the issue:

![20180525_182004](https://user-images.githubusercontent.com/37875464/40647414-7771c246-6334-11e8-872b-c4ab4f259cf8.gif)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/1196

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is still reproducible with the latest version of "Firefox Notes" application (notes-1_0-qa-v2516 custom built on 25.06.2018) on Pixel (Android 8.0.0), Samsung S8 (Android 8.0.0) and Huawei P8 Lite (Android 6.0)
Considering this I will reopen this issue.

**Comment by vladikoff** [comment]
Thanks for checking this one!!

**Comment by Softvision-MariusComan** [comment]
This issue is still reproducible with the latest version of "Firefox Notes" application (notes-1_0-qa-v2593 custom built on 27.06.2018) on Pixel (Android 8.0.0), Samsung S8 (Android 8.0.0) and Huawei P8 Lite (Android 6.0)
Considering this I am reopening this issue.

**Comment by Softvision-MariusComan** [comment]
This issue is still reproducible with the latest version of "Firefox Notes" application (1.0.3 RC2) on Pixel (Android 8.0.0), Samsung S8 (Android 8.0.0) and Huawei P8 Lite (Android 6.0)
Considering this I am reopening this issue.

**Comment by Softvision-MariusComan** [comment]
This issue is still reproducible with the latest version of "Firefox Notes" application (1.0.3 RC4) on Pixel (Android 8.0.0), Samsung S8 (Android 8.0.0) and Huawei P8 Lite (Android 6.0)
Considering this I am reopening this issue.
![kirk](https://user-images.githubusercontent.com/31243259/42377589-88a33d72-812c-11e8-91f0-50219d64351e.jpg)

**Comment by vladikoff** [comment]
Ok has to be fixed now 🦀

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (1.0.3RC6) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
![d8d](https://user-images.githubusercontent.com/31243259/42437560-23f4762a-8366-11e8-90a8-2c87e9bc8414.jpg)
