### ISSUE TITLE
Hyperlinks format options are canceled when choosing the numbered (or bulleted) list options

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#253]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write a valid hyperlink address into the "Notes" sidebar (eg. http://wikipedia.org)
3. Select the hyperlink and click on one of the following formatting buttons: Font Size, Bold, Italic or Strikethrough.
4. Click on Numbered List (or Bulleted List) button and observe the hyperlink.

[Expected result]:
- The hyperlink is displayed as a numbered (or bulleted) list presenting the same formatting option from step 3.

[Actual result]:
- The hyperlink is displayed as a numbered (or bulleted) list, but the previous formatting option is canceled.

[Notes]:
- This issue is not reproducible when having more than one Hyperlinks selected.
- Attached a screen recording of the issue:

![list options](https://user-images.githubusercontent.com/26000308/30915176-9eeb67f6-a39e-11e7-896b-04f801f96308.gif)

**Comment by Natim** [comment]
Fixed in 75c751452146e488b39e7b8c86fb38df4bdc3ecb

**Comment by SoftVision-CarmenFat** [comment]
The issue is still reproducible on the latest Firefox Notes version (1.8.0rc3).

**Comment by Natim** [comment]
@cedricium I think this is due to the fact that we recreate the node. Do you know how we can update it instead?

**Comment by Natim** [comment]
Similar reason for https://github.com/mozilla/notes/issues/269

**Comment by cedricium** [comment]
@Natim I'll need to investigate this, but I suspect you're right about the node being recreated.

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with the latest Firefox Notes v.1.8.0dev (built today 10/24/2017).
