### ISSUE TITLE
"Undo" option doesn't work properly on previously formatted text

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#260]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write something on the "Notes" editable area.
3. Select the written text and click on one of the formatting options buttons.
4. Press Ctrl + Z keys and observe what happens next.

[Expected result]:
- The written text is deleted.

[Actual result]:
- The first letter of the text remains displayed.

[Notes]:
- This is also reproducible using the "Undo" option from the context menu.
- Attached a screen recording of the issue:

![undo](https://user-images.githubusercontent.com/26000308/30975398-db7196e6-a47a-11e7-8455-eb3a1ce92c0b.gif)

**Comment by Natim** [comment]
I can't reproduce in the QuillJS playground, it has been fixed in QuillJS 1.3.3

**Comment by Natim** [comment]
Fixed in #241 2.0.0a2

**Comment by SoftVision-CarmenFat** [comment]
Tested this with both latest Notes v.2.0.0a2 and QuillJS Playground and still was able to reproduce the issue (but this time, only by using the "Undo" option from the context menu):

![playground](https://user-images.githubusercontent.com/26000308/31488088-56509e50-af45-11e7-877c-cbf1b9ffd778.gif)

**Comment by SoftVision-EmilPasca** [comment]
This issue is still reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.

**Comment by Natim** [comment]
This would be handled with the beforeinput event implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=970802

**Comment by vladikoff** [comment]
This should be fixed with the new editor!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 07/18/2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
