### ISSUE TITLE
A blue border wrongly appears when you long click on "Font size" options

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#438]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest "Firefox Notes" add-on v1.9.0dev installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Font size" button.
3. Long click one of the options and observe the behavior.

[Expected result]:
- The font size option is highlighted with a grey color.

[Actual result]:
- A blue border appears.

[Notes]:
- Here is a screen recording of the issue:
![blue border](https://user-images.githubusercontent.com/31244235/33180303-e8de67c0-d074-11e7-99f5-105d776ada00.gif)
![blueborder](https://user-images.githubusercontent.com/31244235/33180311-f05d1410-d074-11e7-9556-73c465f36b1b.png)

**Comment by vladikoff** [comment]
Filed https://github.com/ckeditor/ckeditor5-heading/issues/91 to check if by-design or not

**Comment by Natim** [comment]
I believe this is fixed today.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is still reproducible using the latest Firefox Notes v4.1.0dev, on latest Nightly build 62.0a1, on Windows 10 x64, Mac 10.13 and Arch Linux 4.12.

Considering this, I'm going to reopen this issue.

**Comment by vladikoff** [comment]
👍

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! The issue is no longer reproducible using the latest Firefox Notes v4.2.0dev (custom built on 2018-06-21), on latest Nightly build 62.0a1 and Firefox Release 60.0.2. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
