### ISSUE TITLE
Disable the "Sync Your Notes" button while "Saved at (hour)" status is displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#479]
**[Notes]:**
- If you press the "Sync Your Notes" button while "Saved at (hour)" status is displayed then the content will be duplicated.
- If you spam click the "Sync Your Notes" button, then the content will be multiplied exponentially with the number of clicks made which can lead to the sidebar freezing and becoming unresponsive.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b7) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Write something in the sidebar.
3. Observe the "Sync Your Notes" button while the "Saved at (hour)" status is displayed.

**[Expected result]:**
- The "Sync Your Notes" button is inactive.

**[Actual result]:**
- The "Sync Your Notes" button is active and actionable. 

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue1](https://user-images.githubusercontent.com/31243259/33610543-7aa04ff8-d9d4-11e7-8969-cb56f66b86ab.gif)

**Comment by vladikoff** [comment]
Good find!!

**Comment by vladikoff** [comment]
@Natim we should fix this for the RC IMHO

**Comment by vladikoff** [comment]
Should be fixed in https://github.com/mozilla/notes/commit/643eb26a4fdac117e50a10cb225cebd85c2ff951 and in landed in the next version.

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible with the latest "Firefox Notes" add-on version (2.0.0rc2) installed. Considering this I will reopen the issue.

**Comment by Natim** [comment]
Fixed with 529b896

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (2.0.0rc3) on the latest Firefox release and Nightly.
