### ISSUE TITLE
The "Backspace" button wrongly goes back one page after clicking the sync button and selecting all text

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#480]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b7) installed.
- Have content in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to a website in the same tab.
2. Click the "Sync Your Notes" button and press "Ctrl+A".
3. Press the "Backspace" key and observe the behavior.

**[Expected result]:**
- All the content is deleted.

**[Actual result]:**
- The content is not deleted and the opened website goes back one page instead. 

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33610829-2c6cd2ec-d9d5-11e7-86e5-63581b4ea4f8.gif)

**Comment by vladikoff** [comment]
Some focusing + keyboard bug either with CKEditor or Firefox.

Moving to Editor milestone

**Comment by Natim** [comment]
I believe this is fixed.

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6) installed. Considering this, I am reopening the issue.
Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35865983-a15db8a4-0b5e-11e8-87de-a0b78bab4a30.gif)

**Comment by vladikoff** [comment]
we can try capturing the backspace event when synced focused...

**Comment by vladikoff** [comment]
we can also try returning focus on the textarea
