### ISSUE TITLE
The bulleted/numbered list is partially visible if it's created at the end of the "Notes" sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#523]
[Notes]:
- The list notation becomes fully visible when you start typing.

[Affected versions]:
- Firefox 57.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Insert enough text until the scrollbar appears.
3. Press "Enter" key.
4. Click the "Numbered list" button and observe the behavior.

[Expected result]:
- "1" appears fully visible.

[Actual result]:
- "1" appears partially visible.

[Additional notes]:
- This issue is also reproducible with the "Bulleted list".
- Here is a screen recording of the issue:
![partially visible](https://user-images.githubusercontent.com/31244235/34159666-b1e1bb2e-e4d2-11e7-86d2-a99bda5a721f.gif)

**Comment by Natim** [comment]
I believe this is fixed.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is still reproducible using Firefox Notes [v2.2.0rc5](https://github.com/mozilla/notes/pull/619#issuecomment-362590630), or Firefox Notes v2.2.0dev (custom build 2018-02-05), on latest Nightly build 60.0a1 (2018-02-04), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12. 

Considering this, I'm going to reopen this issue until it's fixed.
