### ISSUE TITLE
The bottom part wrongly bounces while resizing the window

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#600]
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-01-19) installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Vertically resize the browser.
3. Observe the bottom part of the "Notes" sidebar.

[Expected result]:
- Nothing happens with the bottom part, it's steady.

[Actual result]:
- The bottom part bounces.

[Notes]:
- This issue is also reproducible if you diagonally resize the browser.
- This issue is also reproducible with Firefox Notes installed from Test Pilot experiment [page](https://testpilot.firefox.com/experiments/notes) and with Firefox Notes v2.1.1.rc2.
- Here is a screen recording of the issue:
![look at the bottom](https://user-images.githubusercontent.com/31244235/35151034-62c48cae-fd25-11e7-9c9c-33f163411de8.gif)

**Comment by johngruen** [comment]
@Natim possible fix for this would be to change the body height to `100vh` otherwise, we can close this.

**Comment by Softvision-CristinaBadescu** [comment]
Since the fix did not resolve the issue and it was also reverted, I'm going to reopen this in order to track it.

**Comment by vladikoff** [comment]
This should be fixed in latest version...

**Comment by Softvision-CristinaBadescu** [comment]
I've tested this issue and is still reproducible using the latest Firefox Notes v4.2.0dev, on latest Nightly build 63.0a1, on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04 x64.
Considering this, I'm going to reopen the issue.
