### ISSUE TITLE
Unnecessary horizontal scroll in the Sidebar's editing area

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#94]
[Notes]:
- The issue is also reproducible by pressing and holding the "Space" key in the content area.
- The issue is reproducible even with the Sidebar expanded at maximum. 

[Affected versions]:
- Firefox 54.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.3 -dev, built on 20/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Press middle click on the Sidebar's editing area and slowly move the mouse to the right.
3. Observe what happens with the Sidebar.

[Expected result]:
- Nothing happens, no horizontally scrolling is performed. 

[Actual result]:
- Sidebar is scrolled horizontally and displays an empty content area.

[Additional Notes]:
- Please see the following screencast:

![scrolling](https://user-images.githubusercontent.com/26000308/27345449-6712e0c4-55f2-11e7-803a-5c4a9251a2fe.gif)

**Comment by vladikoff** [comment]
Thanks for the issue, yeah we will need to fix that

**Comment by SoftVision-CarmenFat** [comment]
Hi @vladikoff,

I tested this on the latest Notes version (dev built on 6/23/2017).

Middle click can't be used any longer on the editing area, but pressing and holding the "Space" key will still horizontally scroll the Sidebar to a non-editing area.
Please note that after using the "Space" key to scroll the Sidebar, some combinations of keyboard shortcuts can also be used for scrolling horizontally:
- "Tab" + "Right/Left arrow" keys
- "Ctrl" + "Right/Left arrow" keys.

**Comment by Natim** [comment]
> holding the "Space" key will still horizontally scroll the Sidebar to a non-editing area.

I can confirm and reproduce this, it is only with the space key though 👾

**Comment by Natim** [comment]
Refs:
 - https://bugzilla.mozilla.org/show_bug.cgi?id=1343567
 - https://bugzilla.mozilla.org/show_bug.cgi?id=1351432

**Comment by vladikoff** [comment]
:(

**Comment by Natim** [comment]
I believe this was fixed.

**Comment by SoftVision-CarmenFat** [comment]
Hi @natim,

The behavior mentioned in comment 3 is still reproducible on Notes v.2.0.0a2.

**Comment by johngruen** [comment]
Based on Quill's own editor demos this seems resolvable. Worth a bit more investigation

**Comment by vladikoff** [comment]
Should be fixed in `master`. please let us know!

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest version of Notes built on 11/23/2017.
